; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rpipico2]
platform = raspberrypi
board = rpipico2
framework = arduino
upload_port = COM8
monitor_speed = 115200
board_build.filesystem_size = 1M
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.12.0
	SparkFun/SparkFun BMP581 Arduino Library@^1.0.0
	weoiss/ICM-42688@1.0.1
