#pragma once

#define AUTO_VERSION "V1.1.1_28_ea0b696"
#define ASTRONAV_BUILD_PRODUCTION_DATE "22-29-22-09-2026"
#define ASTRONAV_BUILD_PRODUCTION_SECOND 54
#define ASTRONAV_BUILD_SERIAL_NUMBER UINT32_C(0)
#define ASTRONAV_BUILD_WARRANTY_SIGNATURE UINT32_C(0xD3B2F181)
#define ASTRONAV_BUILD_HARDWARE_MAJOR 1
#define ASTRONAV_BUILD_HARDWARE_MINOR 1
#define ASTRONAV_BUILD_WARRANTY_SIGNATURE_OFFICIAL 1
#define ASTRONAV_BUILD_INITIAL_FIRMWARE_MAJOR 1
#define ASTRONAV_BUILD_INITIAL_FIRMWARE_MINOR 1
#define ASTRONAV_BUILD_INITIAL_FIRMWARE_PATCH 1
#define ASTRONAV_BUILD_FIRMWARE_AHEAD_COUNT 28
#define ASTRONAV_BUILD_FIRMWARE_COMMIT_SHA "ea0b696"
