#pragma once

#define AUTO_VERSION "V1.1.1_3_874f40e"
#define ASTRONAV_BUILD_PRODUCTION_DATE "11-10-05-09-2026"
#define ASTRONAV_BUILD_PRODUCTION_SECOND 28
#define ASTRONAV_BUILD_SERIAL_NUMBER UINT32_C(0)
#define ASTRONAV_BUILD_WARRANTY_SIGNATURE UINT32_C(0xB0E658DF)
#define ASTRONAV_BUILD_HARDWARE_MAJOR 1
#define ASTRONAV_BUILD_HARDWARE_MINOR 1
#define ASTRONAV_BUILD_WARRANTY_SIGNATURE_OFFICIAL 1
#define ASTRONAV_BUILD_INITIAL_FIRMWARE_MAJOR 1
#define ASTRONAV_BUILD_INITIAL_FIRMWARE_MINOR 1
#define ASTRONAV_BUILD_INITIAL_FIRMWARE_PATCH 1
#define ASTRONAV_BUILD_FIRMWARE_AHEAD_COUNT 3
#define ASTRONAV_BUILD_FIRMWARE_COMMIT_SHA "874f40e"
