#pragma once

#define AUTO_VERSION "firmware-v1.1.0"
#define ASTRONAV_BUILD_PRODUCTION_DATE "18-27-30-08-2026"
#define ASTRONAV_BUILD_PRODUCTION_SECOND 0
#define ASTRONAV_BUILD_SERIAL_NUMBER UINT32_C(3574489149)
#define ASTRONAV_BUILD_WARRANTY_SIGNATURE UINT32_C(0xACE798DF)
#define ASTRONAV_BUILD_HARDWARE_MAJOR 1
#define ASTRONAV_BUILD_HARDWARE_MINOR 1
#define ASTRONAV_BUILD_WARRANTY_SIGNATURE_OFFICIAL 1
#define ASTRONAV_BUILD_INITIAL_FIRMWARE_MAJOR 1
#define ASTRONAV_BUILD_INITIAL_FIRMWARE_MINOR 1
#define ASTRONAV_BUILD_INITIAL_FIRMWARE_PATCH 0
